//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaOtomasyonLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HastaOtomasyonLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Context xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Doktorlar&gt;
        ///    &lt;Doktor&gt;
        ///      &lt;Ad&gt;Celil&lt;/Ad&gt;
        ///      &lt;Soyad&gt;Karahasanoğlu&lt;/Soyad&gt;
        ///      &lt;TCKN&gt;81323909395&lt;/TCKN&gt;
        ///      &lt;Telefon&gt;5394084969&lt;/Telefon&gt;
        ///      &lt;DogumTarihi&gt;1994-10-13T11:12:57&lt;/DogumTarihi&gt;
        ///      &lt;Cinsiyet&gt;Erkek&lt;/Cinsiyet&gt;
        ///      &lt;Brans&gt;FizikTedavi&lt;/Brans&gt;
        ///      &lt;BagliHemsireler /&gt;
        ///      &lt;Maas&gt;3000&lt;/Maas&gt;
        ///    &lt;/Doktor&gt;
        ///    &lt;Doktor&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfDoktor xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Doktor&gt;
        ///    &lt;Ad&gt;Celil&lt;/Ad&gt;
        ///    &lt;Soyad&gt;Karahasanoğlu&lt;/Soyad&gt;
        ///    &lt;TCKN&gt;81323909395&lt;/TCKN&gt;
        ///    &lt;Telefon&gt;5394084969&lt;/Telefon&gt;
        ///    &lt;DogumTarihi&gt;1994-10-13T11:12:57&lt;/DogumTarihi&gt;
        ///    &lt;Cinsiyet&gt;Erkek&lt;/Cinsiyet&gt;
        ///    &lt;Brans&gt;FizikTedavi&lt;/Brans&gt;
        ///    &lt;BagliHemsireler /&gt;
        ///    &lt;Maas&gt;3000&lt;/Maas&gt;
        ///  &lt;/Doktor&gt;
        ///  &lt;Doktor&gt;
        ///    &lt;Ad&gt;Selahattin Erk&lt;/Ad&gt;
        ///    &lt;So [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Doktorlar {
            get {
                return ResourceManager.GetString("Doktorlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfHasta xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Hasta&gt;
        ///    &lt;Ad&gt;Samet&lt;/Ad&gt;
        ///    &lt;Soyad&gt;Metin&lt;/Soyad&gt;
        ///    &lt;TCKN&gt;79690574378&lt;/TCKN&gt;
        ///    &lt;Telefon&gt;3213213211&lt;/Telefon&gt;
        ///    &lt;DogumTarihi&gt;1859-06-02T11:15:04&lt;/DogumTarihi&gt;
        ///    &lt;Cinsiyet&gt;Erkek&lt;/Cinsiyet&gt;
        ///  &lt;/Hasta&gt;
        ///&lt;/ArrayOfHasta&gt;.
        /// </summary>
        internal static string Hastalar {
            get {
                return ResourceManager.GetString("Hastalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfHemsire xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Hemsire&gt;
        ///    &lt;Ad&gt;Nazlı&lt;/Ad&gt;
        ///    &lt;Soyad&gt;Coşkun&lt;/Soyad&gt;
        ///    &lt;TCKN&gt;53617844453&lt;/TCKN&gt;
        ///    &lt;Telefon&gt;5675434312&lt;/Telefon&gt;
        ///    &lt;DogumTarihi&gt;1997-02-12T11:13:58&lt;/DogumTarihi&gt;
        ///    &lt;Cinsiyet&gt;Kadın&lt;/Cinsiyet&gt;
        ///    &lt;Brans&gt;GenelCerrahi&lt;/Brans&gt;
        ///    &lt;Maas&gt;1404&lt;/Maas&gt;
        ///  &lt;/Hemsire&gt;
        ///  &lt;Hemsire&gt;
        ///    &lt;Ad&gt;Bora&lt;/Ad&gt;
        ///    &lt;Soyad&gt;Gürpınar&lt;/Soyad&gt;
        ///    &lt;TCKN&gt;70985 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hemşireler {
            get {
                return ResourceManager.GetString("Hemşireler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfPersonel xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Personel&gt;
        ///    &lt;Ad&gt;Mahmun&lt;/Ad&gt;
        ///    &lt;Soyad&gt;Ünlü&lt;/Soyad&gt;
        ///    &lt;TCKN&gt;72126906400&lt;/TCKN&gt;
        ///    &lt;Telefon&gt;1234321221&lt;/Telefon&gt;
        ///    &lt;DogumTarihi&gt;1888-06-02T11:14:38&lt;/DogumTarihi&gt;
        ///    &lt;Cinsiyet&gt;Erkek&lt;/Cinsiyet&gt;
        ///    &lt;PersonelBrans&gt;Temizlikci&lt;/PersonelBrans&gt;
        ///    &lt;Maas&gt;1404&lt;/Maas&gt;
        ///  &lt;/Personel&gt;
        ///&lt;/ArrayOfPersonel&gt;.
        /// </summary>
        internal static string Personeller {
            get {
                return ResourceManager.GetString("Personeller", resourceCulture);
            }
        }
    }
}
